spring.application.name=backend

# OAuth2 via GitHub
spring.security.oauth2.client.registration.github.client-id=${OAUTH2_CLIENT_ID_LOCAL_DEPLOYMENT}
spring.security.oauth2.client.registration.github.client-secret=${OAUTH2_CLIENT_SECRET_LOCAL_DEPLOYMENT}
spring.security.oauth2.client.registration.github.scope=none

# Redirection URL on successful authentication
app.url=${OAUTH2_SUCCESS_URL}

# Connect to PostGRESql instance on Aiven
spring.datasource.url=${POSTGRES_SERVICE_URI}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configure JPA
spring.jpa.hibernate.ddl-auto=update